LANGUAGE_OPTIONS = ["English", "Spanish", "French", "German", "Italian", "Portuguese"]

STOPWORDS = {
    "English": {
        "the",
        "and",
        "is",
        "in",
        "to",
        "of",
        "a",
        "for",
        "on",
        "with",
        "as",
        "that",
        "this",
        "it",
        "by",
    },
    "Spanish": {
        "el",
        "la",
        "los",
        "las",
        "y",
        "o",
        "en",
        "de",
        "que",
        "por",
        "para",
        "con",
        "es",
        "un",
        "una",
    },
    "French": {
        "le",
        "la",
        "les",
        "et",
        "ou",
        "en",
        "de",
        "que",
        "pour",
        "avec",
        "est",
        "un",
        "une",
        "des",
    },
    "German": {
        "der",
        "die",
        "das",
        "und",
        "oder",
        "in",
        "von",
        "zu",
        "mit",
        "ist",
        "ein",
        "eine",
        "den",
        "dem",
    },
    "Italian": {
        "il",
        "la",
        "i",
        "gli",
        "le",
        "e",
        "o",
        "in",
        "di",
        "per",
        "con",
        "è",
        "un",
        "una",
    },
    "Portuguese": {
        "o",
        "a",
        "os",
        "as",
        "e",
        "ou",
        "em",
        "de",
        "que",
        "para",
        "com",
        "é",
        "um",
        "uma",
    },
}

LANGUAGE_HINTS = {
    "English": {"the", "and", "is", "of", "to", "with", "that"},
    "Spanish": {"el", "la", "que", "y", "de", "para"},
    "French": {"le", "la", "que", "et", "de", "pour"},
    "German": {"der", "die", "und", "zu", "mit", "ist"},
    "Italian": {"il", "la", "che", "e", "di", "per"},
    "Portuguese": {"o", "a", "que", "e", "de", "para"},
}


def get_language_config(language_name: str) -> dict:
    return {
        "name": language_name,
        "stopwords": STOPWORDS.get(language_name, set()),
        "hints": LANGUAGE_HINTS.get(language_name, set()),
    }
